### ISSUE TITLE
Grain pile crash

### ISSUE THREAD

**Issue by AnodeCathode** [Lumintorious/TFCStorage#2]
java.lang.NullPointerException
    at net.dries007.tfc.api.capability.food.FoodHandler.getDecayDateModifier(FoodHandler.java:115)
    at net.dries007.tfc.api.capability.food.FoodHandler.calculateRottenDate(FoodHandler.java:201)
    at net.dries007.tfc.api.capability.food.FoodHandler.getCreationDate(FoodHandler.java:69)
    at net.dries007.tfc.api.capability.food.FoodHandler.serializeNBT(FoodHandler.java:152)
    at net.dries007.tfc.api.capability.food.FoodHandler.serializeNBT(FoodHandler.java:24)
    at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:123)

Full log: https://paste.ee/p/TS6Ox

**Comment by NOTtheMessiah** [comment]
Paste not found. Any supplemental information as to what caused the crash?
