### ISSUE TITLE
Server-side error when trying to place grains

### ISSUE THREAD

**Issue by ACGaming** [Lumintorious/TFCStorage#4]
```
[18:55:09] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@31355dce:
java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at com.lumintorious.tfcstorage.registry.EventHandler$.placeGrainPiles(EventHandler.scala:43) ~[EventHandler$.class:?]
	at com.lumintorious.tfcstorage.registry.EventHandler$.onInteract(EventHandler.scala:28) ~[EventHandler$.class:?]
	at com.lumintorious.tfcstorage.registry.EventHandler.onInteract(EventHandler.scala) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_80_EventHandler_onInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137) [ForgeHooks.class:14.23.5.2855]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[18:55:09] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[18:55:09] [Server thread/ERROR] [FML]: 0: HIGHEST
[18:55:09] [Server thread/ERROR] [FML]: 1: ASM: class com.lumintorious.tfcstorage.registry.EventHandler onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[18:55:09] [Server thread/ERROR] [FML]: 2: NORMAL
[18:55:09] [Server thread/ERROR] [FML]: 3: ASM: class net.dries007.tfc.CommonEventHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:55:09] [Server thread/ERROR] [FML]: 4: LOWEST
[18:55:09] [Server thread/ERROR] [FML]: 5: ASM: class net.dries007.tfc.util.interaction.InteractionManager onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
[18:55:09] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_174822_a(DF)Lnet/minecraft/util/math/RayTraceResult;
	at com.lumintorious.tfcstorage.registry.EventHandler$.placeGrainPiles(EventHandler.scala:43) ~[EventHandler$.class:?]
	at com.lumintorious.tfcstorage.registry.EventHandler$.onInteract(EventHandler.scala:28) ~[EventHandler$.class:?]
	at com.lumintorious.tfcstorage.registry.EventHandler.onInteract(EventHandler.scala) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_80_EventHandler_onInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137) ~[ForgeHooks.class:14.23.5.2855]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

Using the following mod versions:
- TerraFirmaCraft-MC1.12.2-1.7.10.168
- TFCStorage-1.0.7

**Comment by CuteLuoBo** [comment]
The same problem.
Version:
- TFCStorage-1.0.7
- TerraFirmaCraft-MC1.12.2-1.7.10.168

running Server environment
core: CatServer 1.12.2 2a9163f - Forge Mod Loader version 14.23.5.2855

When players use brush monster eggs to generate entities, entities are generated, but brush monster eggs are not consumed, which is a serious bug
